// PDF export utility for business plans

import { BusinessPlan } from "./storage";

export function generatePlanContent(
  title: string,
  idea: string,
  audience: string,
  industry: string,
  differentiator: string,
  plan: BusinessPlan
): string {
  const sections = [
    `AI BUSINESS GENERATOR\n${title}`,
    `\nCORE CONCEPT\n${idea}`,
    `\nTARGET AUDIENCE\n${audience || "Not specified"}`,
    `\nINDUSTRY\n${industry || "Not specified"}`,
    `\nUNIQUE DIFFERENTIATOR\n${differentiator || "Not specified"}`,
    `\n\n________________________________________\n`,
    `\nVALUE PROPOSITION\n${plan.valueProposition}`,
    `\n\nCUSTOMER PERSONAS\n${plan.customerPersonas.join("\n")}`,
    `\n\nCOMPETITIVE ANALYSIS\n${plan.competitiveAnalysis.join("\n")}`,
    `\n\nREVENUE MODEL\n${plan.revenueModel}`,
    `\n\nMVP FEATURES\n${plan.mvpFeatures.join("\n")}`,
    `\n\nGO-TO-MARKET STRATEGY\n${plan.goToMarketStrategy.join("\n")}`,
    `\n\nPITCH DECK OUTLINE\n${plan.pitchDeckOutline.join("\n")}`,
    `\n\n________________________________________`,
    `\n\nGenerated by AI Business Generator`,
    `Date: ${new Date().toLocaleDateString()}`
  ];

  return sections.join("");
}

export function downloadAsText(
  title: string,
  idea: string,
  audience: string,
  industry: string,
  differentiator: string,
  plan: BusinessPlan
): void {
  const content = generatePlanContent(title, idea, audience, industry, differentiator, plan);
  const element = document.createElement("a");
  const file = new Blob([content], { type: "text/plain" });
  element.href = URL.createObjectURL(file);
  element.download = `${title.replace(/\s+/g, "_")}_${Date.now()}.txt`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

export function downloadAsJSON(
  title: string,
  idea: string,
  audience: string,
  industry: string,
  differentiator: string,
  plan: BusinessPlan
): void {
  const data = {
    title,
    createdAt: new Date().toISOString(),
    inputs: {
      startupIdea: idea,
      targetAudience: audience,
      industry,
      differentiator
    },
    businessPlan: plan
  };

  const element = document.createElement("a");
  const file = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  element.href = URL.createObjectURL(file);
  element.download = `${title.replace(/\s+/g, "_")}_${Date.now()}.json`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}
